### ISSUE TITLE
when stable, use `core::arch::arm` to implement `cortex_m::asm`

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cortex-m#101]
this will let us provide the `cortex_m::asm` API on stable without depending on an external assembler.

**Comment by japaric** [comment]
Removing from the RC1 (edition) milestone because thanks to PR #108 this crate no longer on GCC so this is just a nice to have.

**Comment by jonas-schievink** [comment]
We now use Rust's new inline assembly (https://github.com/rust-lang/rust/issues/72016) and an FFI shim to implement `cortex_m::asm`, removing the need for any external tooling. Inline asm has higher chances of being stabilized than `core::arch::arm`, so maybe we should close this issue? (doesn't seem too important to keep tracking this; we can remove the FFI shim once inline asm is stable)

**Comment by adamgreig** [comment]
SGTM. I agree that inline asm getting stabilised looks more likely than all the relevant instructions landing in core::arch::arm, and in any event we need a few assembly routines for some methods anyway.
