### ISSUE TITLE
DWT timer not started on STM32F7xx 

### ISSUE THREAD

**Issue by musitdev** [rust-embedded/cortex-m#144]
RTFM schedule doesn't work on STM32F7xx. After some test at Oxydize with Jorge, we found that the DWT timer is never started. It needs some more configuration.
By adding the line unsafe { (*DWT::ptr()).lar.write(0xC5ACCE55) }; it works.
It should be added to the cortex-m DWT init for STM32F7xx

**Comment by korken89** [comment]
Does this generalize to all Cortex-M7 cores?

**Comment by japaric** [comment]
This needs to be fixed in RTFM; moving to japaric/cortex-m-rtfm#184
