### ISSUE TITLE
Make const-fn default

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/cortex-m#153]
At the moment the cortex-m still hides `const` versions of some functions (especially `Mutex::new()`) behind the `const-fn` feature, but these have worked on stable Rust for some time now.

It looks like this crate does not yet follow the WG [MSRV policy](https://github.com/rust-embedded/wg/blob/master/ops/msrv.md) so I'm not really sure what the MSRV even is, but perhaps we could allow it to be 1.31 and therefore either remove the `const-fn` feature or make it a default.

cc https://github.com/rust-embedded/book/pull/196

**Comment by Disasm** [comment]
I filed a PR to bare-metal with this fix: https://github.com/japaric/bare-metal/pull/18
