### ISSUE TITLE
Read Access to control register

### ISSUE THREAD

**Issue by kanishkarj** [rust-embedded/cortex-m#166]
Hi ! I need access to read from control register. Basically i want to check if the code is currently running in privileged or unprivileged mode. But the thing being, how to initialize an instance of control register? (Cotrex_m:: registers::control::Control)

**Comment by jonas-schievink** [comment]
`cortex_m::register::control::read()`

**Comment by kanishkarj** [comment]
I used that and it was working fine for a while. Then suddenly it started behaving weirdly, despite switching to user mode and to PSP (in an RTOS) the control register showed that the program is currently running in privileged mode and MSP. After debugging for a long time, I tried reading values from the control register directly via inline-asm. Any reason why it happened so? (currently I am using the inline-asm function instead of the one provided by cortex-m crate)

**Comment by jonas-schievink** [comment]
I don't think there's much we can do here, especially without source code. Reading `CONTROL` works fine for me.
