### ISSUE TITLE
Consider getting rid of aligned dependency subtree

### ISSUE THREAD

**Issue by nickray** [rust-embedded/cortex-m#184]
This eventually pulls in two versions of generic-array which is a bit weird. Maybe take over `aligned` and/or `as-slice` and add some feature flags there? Or make `itm::write_aligned` itself an optional feature?

re. https://github.com/rust-embedded/cortex-m/issues/183

**Comment by jonas-schievink** [comment]
Oh *this* is where all the `generic-array` dependencies come from? I was wondering about that.

Pulling in 4 dependencies for a single function seems very excessive, so I'm on board with removing them. We can add our own alignment-enforcing struct to the `itm` module instead.

**Comment by nickray** [comment]
Yeah for some (compatibility?) reason as-slice pulls in both.

**Comment by therealprof** [comment]
Yeah, otherwise you run into weird compatibility problems.

**Comment by nickray** [comment]
None of my dependencies that depend on generic-array use 0.12, so I' be curious what compatibility issues there might be?
