### ISSUE TITLE
Remove Arm server access from CI

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/cortex-m#194]
We currently download the GCC toolchain from the Arm servers during CI, which is unreliable. We should try installing a toolchain via apt-get, since Travis mirrors that internally. Hopefully there's a version that works for us.

**Comment by hug-dev** [comment]
You have [this PPA](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa) that might work. The version is a bit old but supports Armv8-M. It's the one used in the Rust repo `dist-various-1` [Dockerfile](https://github.com/rust-lang/rust/blob/master/src/ci/docker/dist-various-1/Dockerfile).
