### ISSUE TITLE
UB in inline-asm delay function

### ISSUE THREAD

**Issue by ButtNaked** [rust-embedded/cortex-m#195]
UB in higher opt levels with **inline-asm feature**, caused by forgotten asm clobber in asm::delay function.

Example fix:
```            
asm!("1:
      nop
      subs $0, $$1
      bne.n 1b"
      : "+r"(_n / 4 + 1)
      :
      :
      : "cpsr" // <= Added here
      : "volatile");
```

**Comment by jonas-schievink** [comment]
Oh, you need to clobber the status register explicitly? That seems very easy to forget, we should audit all asm for this.

**Comment by adamgreig** [comment]
I've done an audit of all occurrences of `asm!` I could find in rust-embedded and this is the only instance I found which updates the condition flags. Should the fix be `cpsr` or `cc` clobber?

**Comment by therealprof** [comment]
`cspr` should be the right one since it's the name of the register containing the condition flags on ARM. `cc` is some GCC architecture independent magic name to indicate the register holding the condition flags, but I'm not even sure it's universally applicable to non-GCC inline assembly...
