### ISSUE TITLE
check-blobs.sh does nothing

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/cortex-m#254]
Running it modifies all the archives on my system, but doesn't fail.

Since we've started passing `-g` to the assembler, all files now contain system-specific paths and are not reproducible.

**Comment by adamgreig** [comment]
`check-blobs.sh` compares the output of `arm-none-eabi-objdump -Cd`, which does not contain the system-specific paths and the CI seems to be correctly checking that those outputs match, but unfortunately that's not the same as checking the actual `.a` files match byte-for-byte. Can we specify `-g` without causing specific paths to be included?
