### ISSUE TITLE
macOS produces different archives from Linux

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/cortex-m#329]
Seen in https://github.com/rust-embedded/cortex-m/pull/328, this means that running `cargo xtask assemble` on macOS will produce different archives from what CI expects.

Not sure what the cause of this is, or if this is even fixable, but we should make sure that users on macOS can contribute to this crate without problems.

**Comment by therealprof** [comment]
Hm, do we know what the differences are? Let me try that. 😅

**Comment by therealprof** [comment]
The generated code is 100% identical but the order of the symbols in the generated objects is not stable. Interestlingy that's only the case for the non`-lto` archives, the `-lto` archives are fine.

**Comment by therealprof** [comment]
I tried a ton of different options and a few different nightly versions but I couldn't get the symbol order to line up. 🤷🏻‍♂️

**Comment by jonas-schievink** [comment]
Perhaps we should relax the check in CI then

**Comment by therealprof** [comment]
Hm, we could change the check to only verify the `-lto` ones, should be good enough to detect subtle code changes?

**Comment by newAM** [comment]
I'm triaging Cortex-M issues today.

I tried to do the basic CI tasks on an M1 Mac and everything works now as far as I can tell, and we no longer have pre-compiled blob.s

I'm going to close this issue, please re-open if I missed anything!
