### ISSUE TITLE
is ptr() function on `RegisterBlock`'s actually deprecated or not?

### ISSUE THREAD

**Issue by TDHolmes** [rust-embedded/cortex-m#370]
I see that the [`ptr() function`](https://github.com/rust-embedded/cortex-m/blob/ae1d2a62d895dc458784c465e021a010cb75a8b1/src/peripheral/mod.rs#L248) to get the pointer to the register block has the comment "to be deprecated in 0.7", but it's already 0.7 and it isn't deprecated... was this just missed or is it no longer the plan?

**Comment by TDHolmes** [comment]
some context: https://github.com/rust-embedded/cortex-m/pull/235#issuecomment-662046920 / #235

**Comment by adamgreig** [comment]
Oops, I think this was simply missed for 0.7. We can deprecate it in the existing 0.7 series though, and remove it for 0.8.

**Comment by reitermarkus** [comment]
I think this can be closed, right?
