### ISSUE TITLE
`data_overflow.rs` example/test is failing

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/cortex-m#404]
Or rather, it builds successfully. The reason is that these `!` do not work with `errexit`, so a successful build has no consequences:

https://github.com/rust-embedded/cortex-m-rt/blob/5ac023dd9261d67aafbeab018241b4bcc4742152/ci/script.sh#L44-L48

Caught by shellcheck [SC2251](https://github.com/koalaman/shellcheck/wiki/SC2251).

**Comment by newAM** [comment]
I'm triaging Cortex-M issues, I think this one is fixed as of #505, please re-open if not!

**Comment by newAM** [comment]
Actually I didn't fix it in #505, have #542 open to fix.
