### ISSUE TITLE
Tracking issue for stable inline assembly

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/cortex-m#420]
The next stable Rust release, 1.59, will include stable `asm!()` and `global_asm!()` macros that finally permit us to define assembly directly in the crate without needing to distribute precompiled binaries.

I anticipate this will let us remove all the current code to support precompiled binaries, including the outlined-inlined-asm in cortex-m and the `asm.S` in cortex-m-rt, and make all our `inline-asm` features no-ops. Since this shouldn't be a breaking change to users, it could be released as a cortex-m 0.7 backport, or as part of the upcoming 0.8, and as a normal minor 0.7 release for cortex-m-rt.

This issue is for tracking progress/concerns/problems.

**Comment by hannobraun** [comment]
I just stumbled across this issue while doing some research. Can this be closed? I can't find any assembly in this repository that's not within `asm!` or `global_asm!`.
