### ISSUE TITLE
Potential unsound casting from `volatile_register::RW` to the wrapped type

### ISSUE THREAD

**Issue by shinmao** [rust-embedded/cortex-m#485]
Hi, I am wondering whether the casting here is unsound:
https://github.com/rust-embedded/cortex-m/blob/1746a63ca16b68514ea23dcca1543aed00165452/src/peripheral/scb.rs#L172-L174
Based on the definition, the wrapper struct `volatile_register::RW` (let me abbreviate it as `vr` here) didn't have stable layout, and `rustc` would preserve the right to insert padding or reorder the structure. `vr<u32>` should be declared as `transparent`; otherwise, casting it to `u32` could lead to UB such as uninitialized memory exposure to `ptr::read_volatile`.

**Comment by adamgreig** [comment]
Yep, you're right. In practice this is very unlikely to lead to any issues but in principle volatile_register should add a `repr` to the structs. There's an open PR to do so here: https://github.com/japaric/volatile-register/pull/9 but it's not merged yet.

**Comment by Dirbaio** [comment]
volatile-register v0.2.2 is now out, it adds `#[repr(transparent)]` so the pointer cast is now sound.
