### ISSUE TITLE
More-helpful linker errors

### ISSUE THREAD

**Issue by tomhampshire** [rust-embedded/cortex-m#509]
Having just debugged an issue, it is clear that it would have helped me if the following asserts gave some clear information as to _why_/_how_ "The .text section must be placed inside the FLASH memory.". For example, add to this: "It is likely that this is failing because you are using more FLASH than you actually have"
https://github.com/rust-embedded/cortex-m/blob/6b3a5b7fb95fe98fb05ddb4270d2d14709afe99c/cortex-m-rt/link.x.in#L255-L262

**Comment by jamesmunns** [comment]
Errors as it looks today:

```
  = note: rust-lld: error: 
          ERROR(cortex-m-rt): The .text section must be placed inside the FLASH memory.
          Set _stext to an address smaller than 'ORIGIN(FLASH) + LENGTH(FLASH)'
          
          rust-lld: error: 
          ERROR(cortex-m-rt): The .text section must be placed inside the FLASH memory.
          Set _stext to an address smaller than 'ORIGIN(FLASH) + LENGTH(FLASH)'
          
          rust-lld: error: 
          ERROR(cortex-m-rt): The .text section must be placed inside the FLASH memory.
          Set _stext to an address smaller than 'ORIGIN(FLASH) + LENGTH(FLASH)'
```

**Comment by adamgreig** [comment]
Thanks for reporting this.

I think we should change this assert to just check that `_stext` is inside `FLASH` without checking the whole of `.text` fits, and leave that check to the linker instead (which will give a better error message).

Something like:

```
 ASSERT(_stext > ORIGIN(FLASH) && _stext < ORIGIN(FLASH) + LENGTH(FLASH), " 
 ERROR(cortex-m-rt): The .text section must be placed inside the FLASH memory. 
 Set _stext to an address inside the FLASH region.'"); 
```
